baseURL = "https://blog.doufen.org"
languageCode = "zh-CN"
defaultContentLanguage = "zh-CN"
title = "豆坟"                    # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 10                        # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = "UA-139195771-1"   # your google analytics id
disqusShortname = ""                 # your discuss shortname

[author]                             # essential                     # 必需
  name = "豆坟"

[blackfriday]
  smartypants = false

[[menu.main]]                        # config your menu  # 配置菜单
  name = "豆坟"
  weight = 1
  identifier = "doufen"
  url = "https://doufen.org"

[[menu.main]]
  name = "博客"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "分类"
  weight = 30
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "标签"
  weight = 31
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"

[[menu.foot]]
  name = "隐私权政策"
  weight = 1
  identifier = "privacy-policy"
  url = "/privacy-policy/"

[[menu.foot]]
  name = "关于豆坟"
  weight = 10
  identifier = "about"
  url = "/about/"

[params]
  logo = "img/logo.png"
  icon = "img/icon.png"
  subtitle = "我们的精神病角落"                                         # site's subTitle  # 网站二级标题
  footerSlogan = "你站在坟头看风景，看风景的人在天上看你。明月装饰不了你的窗子，也没人拿你装饰TA的梦。"                 # site's footer slogan  # 网站页脚标语
  keywords = ["豆坟", "豆瓣", "豆伴", "douban", "doufen"]               # site's keywords  # 网站关键字
  description = "Hugo theme zozo example site."                        # site's description  # 网站描述
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = true
  appId = "NXXpazFltKA9zkJd0VUs2TWE-gzGzoHsz"
  appKey = "fLdI9lMLmbk6J2LLUI9frjOH"
  placeholder = "评论内容"
  visitor = true

[social]
  github = "https://github.com/doufen-org"
  twitter = "https://twitter.com/doufen_org"
